//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMazeMvc.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankCard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankCard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMazeMvc.Localize.BankCard", typeof(BankCard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCard.
        /// </summary>
        public static string Add_Сard {
            get {
                return ResourceManager.GetString("Add_Сard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankCard.
        /// </summary>
        public static string Bank_Card {
            get {
                return ResourceManager.GetString("Bank_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete сard.
        /// </summary>
        public static string Delete_Сard {
            get {
                return ResourceManager.GetString("Delete_Сard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Id.
        /// </summary>
        public static string Id_Card {
            get {
                return ResourceManager.GetString("Id_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Id:.
        /// </summary>
        public static string Id_Owner {
            get {
                return ResourceManager.GetString("Id_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about bank cards:.
        /// </summary>
        public static string Info_Bank_Card {
            get {
                return ResourceManager.GetString("Info_Bank_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about bank card:.
        /// </summary>
        public static string Info_Bank_Card_One {
            get {
                return ResourceManager.GetString("Info_Bank_Card_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of card.
        /// </summary>
        public static string Number_Of_Card {
            get {
                return ResourceManager.GetString("Number_Of_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveCard.
        /// </summary>
        public static string Remove_Сard {
            get {
                return ResourceManager.GetString("Remove_Сard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .doc.
        /// </summary>
        public static string Save_file_doc {
            get {
                return ResourceManager.GetString("Save_file_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeeAll.
        /// </summary>
        public static string See_All {
            get {
                return ResourceManager.GetString("See_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Month.
        /// </summary>
        public static string Validity_Month {
            get {
                return ResourceManager.GetString("Validity_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity (month/year):.
        /// </summary>
        public static string Validity_Month_Year {
            get {
                return ResourceManager.GetString("Validity_Month_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Year.
        /// </summary>
        public static string Validity_Year {
            get {
                return ResourceManager.GetString("Validity_Year", resourceCulture);
            }
        }
    }
}
